# Generated by Django 5.0.6 on 2024-07-19 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0002_baselobby_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('baselobby_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lobby.baselobby')),
                ('game_status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
            bases=('lobby.baselobby',),
        ),
    ]
